#bridget-ui production environment
services:
  backend:
    build:
      context: ../../backend
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ../../frontend
    ports:
      - "8000:8000"