#bridget-ui development environment
services:
  backend:
    build:
      context: ../../backend
      dockerfile: ../compose/dev/dev-backend.Dockerfile
    volumes:
      - ../../backend:/app/
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../compose/dev/dev-frontend.Dockerfile
    volumes:
      - ../../frontend:/app/
    ports:
      - "8000:8000"