#bridget-ui development environment
services:
  backend:
    build:
      context: ../../backend
      dockerfile: ../compose/dev/dev-backend.Dockerfile
    volumes:
      - ../../backend:/app/
    ports:
      - "3000:3000"